### ISSUE TITLE
to upgrade Qbit to 4.3 and Lib 1.2 

### ISSUE THREAD

**Issue by amlopin** [amefs/quickbox-arm#1]
Hi,  first many thanks for the script, I am currently using it and it is very easy to install it in my weak arm sys.
Have you got any plan to be able to upgrade Qbit to 4.3 and Lib 1.2 ?

Thanks

**Comment by amefs** [comment]
It already available in the latest release. Just type `box update qbittorrent --qb 4.3.0` in your terminal to get the latest qBittorrent.

**Comment by amlopin** [comment]
That´s amazing!!!! Many thanks

**Comment by amlopin** [comment]
Hi again. I did not update Qbit cause in some of my trackers it was not allowed until few days ago.

So, today I tried to update it following your instructions: box install... and box update... It seems to be installed (according with the message on ssh). But in the panel it is showed as not installed: On Service Control Center, qbittorrent is with a red dot
If I try to restart the service pressing "refresh" I got: "Execute failed" "systemctl:restart:qbittorrent"
I tried to login https://my.ip./qbittorrent/ and I got "502 Bad Gateway" from nginx
I tried around 10 times to install it, removing it, upgrading it,... Rebooting the server... Nothing

Any help please
Many thanks

**Comment by amefs** [comment]
please update the script first with `box update quickbox`. After the upgrade completed, try to update qBittorrent again. You can verify qBittorrent service by input `systemctl status qbittorrent@<your user name here>` in ssh. You can also check further info [here](https://en.wiki.ptbox.dev/qbittorrent/).

**Comment by amlopin** [comment]
Oh dear!! How did I miss that? I did not update quickbox before to run the upgrade... 
Anyway, it is working now. Many thanks mate. You take care!
