### ISSUE TITLE
how to remove all of qb-arm?

### ISSUE THREAD

**Issue by luckyjinx** [amefs/quickbox-arm#2]

**Comment by amefs** [comment]
The easiest way is to reinstall the system. 
But you can manually remove if you want:
- pannel under `/srv` 
- script under `/etc/QuiciBox` , `/usr/local/bin/quickbox`
- install lock under `/install`
- bash env `/root/.bash_qb`
- nginx config `/etc/nginx/apps`, `/etc/nginx/conf.d`
