### ISSUE TITLE
soyoustart 5欧盒子安装不了

### ISSUE THREAD

**Issue by cwinu** [amefs/quickbox-arm#4]
ARM-2T Server - Cortex A9 - 2GB - 1x2To

**Comment by amefs** [comment]
请附上日志文件 `/root/quickbox.$PPID.log`

**Comment by cwinu** [comment]
IP address: 54.39.62.224
Server name: ns557860.ip-54-39-62.net
(Active in up to 48hrs time)

The following root account has been configured on the server:
   Username: root

    Password: upNV9kU7EjWj






TR总是密码不对打不开，filebrower无法打开。rt的RSS没有了。
安装过程出问题如下

在 2022-03-15 14:57:19，"amefs" ***@***.***> 写道：

请附上日志文件 /root/quickbox.$PPID.log

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cwinu** [comment]
日志见http://123.btschool.net/123/quickbox.9353.log

**Comment by cwinu** [comment]
TR总是密码不对打不开，filebrower无法打开。rt的RSS没有了。

**Comment by amefs** [comment]
看起来是一个 Debian 9 系统 openssl 的 Bug，这个问题在 x86 版本中也出现过，我可能会考虑推送一个补丁，但由于目前我没有条件测试，不能保证运行正常。

**Comment by amefs** [comment]
如果你可以安装 Debian 10 或者 Ubuntu 18 等系统，应该不会遇到这个问题。

**Comment by cwinu** [comment]
soyoustart 那个5欧盒子只能装OS
Debian 9 Armhf "Stretch" (32bits)

**Comment by cwinu** [comment]
大佬什么时候能推送补丁修复啊

**Comment by amefs** [comment]
请你直接使用 development 分支安装，方法见[此处](https://github.com/amefs/quickbox-arm/blob/development/README_zh.md#%E5%A6%82%E4%BD%95%E7%9B%B4%E6%8E%A5%E5%AE%89%E8%A3%85%E5%BC%80%E5%8F%91%E8%80%85%E6%A8%A1%E5%BC%8F)。测试后如果还遇到问题可以再次反馈，由于构架问题该项目并不会经常维护。

**Comment by cwinu** [comment]
都试过了，不行啊。大佬我发服务器信息给你。你安装试下
SERVER SETTINGS:
IP address: 54.39.62.224
Server name: ns557860.ip-54-39-62.net
(Active in up to 48hrs time)

The following root account has been configured on the server:
   Username: root
    Password: d4P8KutmgP32

**Comment by amefs** [comment]
已经在你提供的服务器做过简易测试，你可以选择修改密码或者再次使用 development 分支重新安装。

**Comment by cwinu** [comment]
感谢大佬。
